### PR TITLE
Add utility to generate meta packages

### PR DESCRIPTION
**Pull request by fluffynuts**
Does what it says on the tin: running `python meta_selector.py` will generate meta-packages for each major dotnet version that is already represented in the Casks folder (ie this must be run after anything that generates version-specific formulae in the Casks folder.

I've tested by pointing homebrew on the test mac I have here to my fork, and I can install the meta-package for, eg, dotnet-sdk7, and it will pull in the latest version of dotnet 7 if I don't already have it installed.

### CODE REVIEW

**Comment by fluffynuts** [comment]
@isen-ng do you have a moment to look at this?

**Comment by isen-ng** [comment]
Hey @fluffynuts, sorry for the delay.
I was away from my computer for 2 weeks but now I'm back.

I'll take a good look within this few days.

**Comment by fluffynuts** [comment]
btw, I can see the failures from the validation script - i'll look into those when I get a gap; `brew` doesn't complain about these, by the way - the meta packages work as expected - but I'd like to pass your existing tests (:

**Comment by fluffynuts** [comment]
hey @isen-ng I'm trying to attend to the errors raised in your automated github actions, but for some reason, even after enabling them, I don't see them running in my forked repo - any ideas?

**Comment by isen-ng** [comment]
@fluffynuts 

```
audit for dotnet-sdk3: failed
 - GitHub fork (not canonical repository)
```

I think this is a check from brew audit to make sure that casks do not download from forks. I think we can switch the url to any existing file from my repo and after this merged, we can alter the URL to point to `META.md`.

**Comment by isen-ng** [comment]
Right after merging, I just realized that there is no README section for these packages and `meta_selector` doesn't update README to define which version the meta packages are referring to

**Comment by fluffynuts** [comment]
O sorry, I didn't realise that was a thing. I'll look into it.

**Comment by fluffynuts** [comment]
@isen-ng apologies, I've completely forgotten about this - thanks for merging the PR (for some reason, I still had this in my head as open...). 

Do you want more entries in the initial table of Versions?
image

Or would you prefer a section for the meta packages themselves? ie something like:

---

## Meta packages
This cask also provides meta formulae for each major version of dotnet, pointing to the current latest release for that version:

Version | .NET SDK |
--------|-----------|
7          |  7.0.408
8          |  8.0.204

By installing the meta-formula, you can easily keep up to date with the latest release for each dotnet major version.
---

**Comment by isen-ng** [comment]
@fluffynuts Sorry for the late response.

I think a separate section will be much better

**Pull request merged**
