### PR TITLE
Add dotnet-sdk-5.0.100 (RC 1)

### PR DESCRIPTION
**Pull request by dahlia**
To have a try at .NET 5 in advance, this adds [.NET 5 RC 1][1].

[1]: https://github.com/dotnet/core/blob/master/release-notes/5.0/preview/5.0.0-rc.1.md

### CODE REVIEW

**Comment by dahlia** [comment]
The build failed due to `brew audit` errors:

> ~~~~
> audit for dotnet-sdk-5.0.100: failed
>  - cask token should only contain lowercase alphanumeric characters and hyphens
>  - Cask should have a description. Please add a `desc` stanza.
> Error: audit failed for casks: dotnet-sdk-5.0.100
> ~~~~

However, all those rules seem to already have been violated by existing casks…

**Comment by isen-ng** [comment]
Hello @dahlia 
thank you for your PR!

however, this version is already covered by `dotnet-sdk-preview`.
https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/dotnet-sdk-preview.rb

you can install the most current `dotnet-sdk`, any of the casks from this tap, and `dotnet-sdk-preview` side-by-side.
there are no conflicts (except when you try to install from this tap, the same version as the official cask).

**Comment by isen-ng** [comment]
personally, I don't want to support preview version in this tap because it's already covered by the official `dotnet-sdk-preview` cask without conflicts.

and it's quite difficult to maintain an updated preview cask automatically.

**Comment by dahlia** [comment]
> however, this version is already covered by `dotnet-sdk-preview`.


I wasn't aware of that! Thanks for letting me know that. I happily close this. 😆

**Comment by pgrm** [comment]
@isen-ng I get the following error when trying to mix an sdk from these casks with the sdk-preview: `It seems there is already a Binary at '/usr/local/bin/dotnet'.` any idea how to resolve that?

**Comment by isen-ng** [comment]
@pgrm Sorry for the late reply.

I looked at the sdk-preview cask again and it seems to me that the sdk-preview cask is designed to conflict with the sdk cask.
which means that the sdk-preview cask will conflict with the latest cask from this tap.

I don't have a mac with me right now, but i believe this is the line of code causing the issue:
https://github.com/isen-ng/homebrew-dotnet-sdk-versions/blob/master/Casks/dotnet-sdk3-1-400.rb#L20

I'm not sure when I can get my hands on a mac (my new job insisted to issue a windows to me), so if any possibilities to help to check of the cask continues to work for you if we delete that line, would be greatly appreciated.

**Pull request closed without merging**
